webtalk_init -webtalk_dir /home/ecestudent/ECE/Spring2019/ECE3700/ClockDivider/ClockDivider.sim/sim_1/behav/xsim/xsim.dir/clkTest_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Feb  8 16:17:03 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "178894513_207303412_207651036_367" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d5e6cf27-35b3-4535-87b7-136c8b4833d8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7d3a3b74242e4286af0afc2d954391e3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS Linux release 7.6.1810 (Core)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3605.053 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "124332_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2474470283 -regid "178894513_207303412_207651036_367" -xml /home/ecestudent/ECE/Spring2019/ECE3700/ClockDivider/ClockDivider.sim/sim_1/behav/xsim/xsim.dir/clkTest_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/ecestudent/ECE/Spring2019/ECE3700/ClockDivider/ClockDivider.sim/sim_1/behav/xsim/xsim.dir/clkTest_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/ecestudent/ECE/Spring2019/ECE3700/ClockDivider/ClockDivider.sim/sim_1/behav/xsim/xsim.dir/clkTest_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
